---

- name: print out the hostname of target
  command: hostname

- name: create docker-compose.yml
  template:
    src: server/docker-compose.yml.j2
    dest: docker-compose.yml

- name: create tinc dir
  file:
    path: tinc/{{ netname }}/hosts
    state: directory

- name: create clients dir
  file:
    path: clients
    state: directory

- name: debug stuff
  debug:
    msg: "{{ item.name }}"
  loop: "{{ clients }}"

- name: add client dirs
  file:
    path: clients/{{ item.name }}/{{ netname }}
    state: directory
    recurse: true
  loop: "{{ clients }}"

- name: create tinc.conf
  template:
    src: server/tinc.conf.j2
    dest: tinc/{{ netname }}/tinc.conf

- name: create client tinc.conf files
  template:
    src: clients/tinc.conf.j2
    dest: clients/{{ item.name }}/{{ netname }}/tinc.conf
  loop: "{{ clients }}"

- name: create client host files in client dir
  template:
    src: clients/host_file.j2
    dest: clients/{{ item.name }}/{{ netname }}/{{ item.name }}
  loop: "{{ clients }}"

- name: tinc server host file
  template:
    src: server/host.j2
    dest: tinc/{{ netname }}/hosts/{{ external_host_name }}

- name: make tinc server net rsa_key.priv
#  command: docker run --mount type=bind,source="$(pwd)"/tinc,target=/etc/tinc --entrypoint "tincd" vimagick/tinc -n feem -K4096
  command: docker run --mount type=bind,source=/home/danh/Services/tinc/tinc,target=/etc/tinc  --entrypoint "tincd" vimagick/tinc -n feem -K4096
  args:
    creates: tinc/{{ netname }}/rsa_key.priv

- name: write tinc-up
  copy:
    src: tinc-up
    dest: tinc/{{ netname }}/tinc-up
    mode: 0755

- name: write tinc-down
  copy:
    src: tinc-down
    dest: tinc/{{ netname }}/tinc-down
    mode: 0755
